from pathlib import Path
p=Path('index.html'); s=p.read_text()
old="""function questPlaceholderCards(items){return items.map(q=>`<div class=\"info-box\"><div style=\"display:flex;justify-content:space-between;gap:8px\"><b>${q.icon} ${q.name}</b><b>🟡 ${q.reward}</b></div><div class=\"small\" style=\"margin-top:6px\">${q.text}</div><div class=\"small\" style=\"margin-top:9px;opacity:.8\">Ready for tracking rules</div></div>`).join('')}\nfunction renderExtraQuestBoards(){\n const w=document.getElementById('weeklyQuestList'),m=document.getElementById('milestoneQuestList'),c=document.getElementById('challengeQuestList');\n if(w)w.innerHTML=questPlaceholderCards(WEEKLY_QUESTS);\n if(m)m.innerHTML=questPlaceholderCards(MILESTONE_QUESTS);\n if(c)c.innerHTML=questPlaceholderCards(CHALLENGE_QUESTS);\n}"""
new="""function questPlaceholderCards(items){return items.map(q=>`<div class=\"info-box\"><div style=\"display:flex;justify-content:space-between;gap:8px\"><b>${q.icon} ${q.name}</b><b>🟡 ${q.reward}</b></div><div class=\"small\" style=\"margin-top:6px\">${q.text}</div><div class=\"small\" style=\"margin-top:9px;opacity:.8\">Ready for tracking rules</div></div>`).join('')}\nfunction questDropdownCards(items){return items.map((q,i)=>`<details class=\"info-box questDrop\" ${i===0?'open':''}><summary style=\"cursor:pointer;list-style:none;display:flex;align-items:center;justify-content:space-between;gap:8px;font-weight:900\"><span>${q.icon} ${q.name}</span><span style=\"display:flex;align-items:center;gap:8px\"><span>🟡 ${q.reward}</span><span class=\"dropArrow\">▼</span></span></summary><div style=\"border-top:1px solid #315b47;margin-top:10px;padding-top:10px\"><div class=\"small\">${q.text}</div><div class=\"small\" style=\"margin-top:9px;opacity:.8\">Ready for tracking rules</div></div></details>`).join('')}\nfunction renderExtraQuestBoards(){\n const w=document.getElementById('weeklyQuestList'),m=document.getElementById('milestoneQuestList'),c=document.getElementById('challengeQuestList');\n if(w)w.innerHTML=questPlaceholderCards(WEEKLY_QUESTS);\n if(m)m.innerHTML=questDropdownCards(MILESTONE_QUESTS);\n if(c)c.innerHTML=questDropdownCards(CHALLENGE_QUESTS);\n}"""
if old not in s: raise SystemExit('quest placeholder/render block not found')
s=s.replace(old,new,1)
# Add dropdown arrow rotation styling
style_marker='.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.info-box{background:#11291f;border:1px solid #315b47;border-radius:15px;padding:12px}'
style_new=style_marker+'\n    details.questDrop summary::-webkit-details-marker{display:none}\n    details.questDrop .dropArrow{transition:transform .18s ease;font-size:12px}\n    details.questDrop[open] .dropArrow{transform:rotate(180deg)}'
if style_marker not in s: raise SystemExit('style marker not found')
s=s.replace(style_marker,style_new,1)
p.write_text(s)
