from pathlib import Path
p=Path('index.html')
s=p.read_text()
css='''\n    /* Compact battle layout: keep the full battle controls visible without scrolling on phones */\n    body.battle-mode{overflow:hidden}\n    body.battle-mode #app{height:100dvh;min-height:100dvh;padding:calc(env(safe-area-inset-top) + 2px) 8px calc(72px + env(safe-area-inset-bottom));overflow:hidden}\n    body.battle-mode .topbar{display:none}\n    body.battle-mode #battleScreen{height:100%;display:flex;flex-direction:column;gap:5px;overflow:hidden}\n    body.battle-mode #battleScreen>.hero{margin:0!important;padding:5px 8px!important;border-radius:14px;flex:0 0 auto}\n    body.battle-mode #battleScreen>.hero .small{font-size:10px}\n    body.battle-mode #battleScreen>.hero b{font-size:14px}\n    body.battle-mode #battleScreen .battle-ui{margin:0;gap:5px;flex:0 0 auto}\n    body.battle-mode #battleScreen .battle-ui .pill{padding:4px 7px;font-size:12px}\n    body.battle-mode #startWave{padding:7px 8px!important;font-size:12px;line-height:1.05;min-height:38px}\n    body.battle-mode #battleScreen .map-wrap{flex:1 1 auto;min-height:0;border-radius:14px;border-width:2px}\n    body.battle-mode #game{height:100%;width:100%;aspect-ratio:auto;object-fit:contain}\n    body.battle-mode #message{margin:0;min-height:14px;font-size:11px;line-height:14px;flex:0 0 14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n    body.battle-mode #battleScreen .battle-deck{margin:0;gap:5px;flex:0 0 76px}\n    body.battle-mode #battleScreen .battle-card{min-height:72px;padding:3px 2px;border-radius:10px}\n    body.battle-mode #battleScreen .battle-card .portrait{width:34px;height:34px;margin-bottom:1px}\n    body.battle-mode #battleScreen .battle-card .emoji{font-size:23px}\n    body.battle-mode #battleScreen .battle-card b{font-size:12px;line-height:1.05;display:block}\n    body.battle-mode #battleScreen .battle-card .cost{font-size:10px}\n    body.battle-mode #battleScreen>div:last-of-type{margin-top:0!important;gap:5px!important;flex:0 0 40px}\n    body.battle-mode #speedBtn,body.battle-mode #autoWaveBtn,body.battle-mode #quitBtn{padding:7px 6px!important;font-size:11px;min-height:36px}\n    body.battle-mode .nav{padding-top:4px;padding-bottom:calc(4px + env(safe-area-inset-bottom))}\n    body.battle-mode .nav button{padding:3px 2px;font-size:10px}\n    body.battle-mode .nav .ico{font-size:20px}\n    @media(max-height:760px){\n      body.battle-mode #battleScreen .battle-deck{flex-basis:68px}\n      body.battle-mode #battleScreen .battle-card{min-height:64px}\n      body.battle-mode #battleScreen .battle-card .portrait{width:30px;height:30px}\n      body.battle-mode #message{display:none}\n    }\n'''
if '</style>' not in s: raise SystemExit('style end missing')
s=s.replace('</style>',css+'\n  </style>',1)
old='''function showScreen(id){\n  document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));'''
new='''function showScreen(id){\n  document.body.classList.toggle("battle-mode",id==="battleScreen");\n  document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));'''
if old not in s: raise SystemExit('showScreen marker missing')
s=s.replace(old,new,1)
p.write_text(s)
