from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8');marker='WORM_STAMPEDE_V1'
if marker in s: print('Already applied');raise SystemExit(0)
old='worm:{name:"Worm",emoji:"🪱",rarity:"Common",cost:42,range:110,rate:1/1.30,dmg:16,color:"#b87",desc:"Throws globs of sludge and mud that splatter enemies."},'
new='worm:{name:"Worm",emoji:"🪱",rarity:"Common",cost:42,range:110,rate:1/1.30,dmg:16,color:"#b87",desc:"Throws globs of sludge and mud. At Level 10, every 8th attack triggers Worm Stampede: worms burst from the ground beneath up to 8 enemies in range, each hit dealing 1.5x current tower damage."},'
if old not in s: raise RuntimeError('Updated Worm card anchor not found')
s=s.replace(old,new,1)
old_attack='''  // WORM_MUD_SHOT_V1: sludge/mud projectile attack.\n  if(t.key==="worm"){target.hp-=dmg;battle.shots.push({x:t.x,y:t.y-4,tx:target.x,ty:target.y,life:.34,maxLife:.34,type:"wormMud",spin:Math.random()*6.28});t.cd=cardRate(t.key);return;}'''
new_attack='''  // WORM_MUD_SHOT_V1: sludge/mud projectile attack.\n  // WORM_STAMPEDE_V1: Level 10 every 8th attack erupts beneath up to 8 enemies.\n  if(t.key==="worm"){\n    let stampede=false;if(t.level>=10){t.wormAttackCount=(t.wormAttackCount||0)+1;stampede=t.wormAttackCount%8===0;}\n    if(stampede){const pool=battle.enemies.filter(e=>!e.dead&&e.hp>0&&Math.hypot(e.x-t.x,e.y-t.y)<=range).slice(0,8);for(let i=0;i<pool.length;i++){const e=pool[i];e.hp-=dmg*1.5;battle.shots.push({x:e.x,y:e.y+22,tx:e.x,ty:e.y,life:.62+i*.035,maxLife:.62+i*.035,type:"wormStampede",delay:i*.035});}battle.shots.push({x:t.x,y:t.y,tx:t.x,ty:t.y,life:.85,maxLife:.85,type:"wormStampedeBanner"});}\n    else{target.hp-=dmg;battle.shots.push({x:t.x,y:t.y-4,tx:target.x,ty:target.y,life:.34,maxLife:.34,type:"wormMud",spin:Math.random()*6.28});}\n    t.cd=cardRate(t.key);return;\n  }'''
if old_attack not in s: raise RuntimeError('Worm attack anchor not found')
s=s.replace(old_attack,new_attack,1)
draw_anchor='    // WORM_MUD_SHOT_DRAW_V1\n'
if draw_anchor not in s: raise RuntimeError('Worm draw anchor not found')
draw='''    // WORM_STAMPEDE_DRAW_V1\n    }else if(s.type==="wormStampede"){const q=1-Math.max(0,s.life)/(s.maxLife||.62),x=s.tx,y=s.ty;ctx.save();ctx.translate(x,y);const rise=Math.sin(Math.min(1,q)*Math.PI)*20;ctx.fillStyle="#493525";ctx.globalAlpha=Math.max(0,1-q*.7);ctx.beginPath();ctx.ellipse(0,8,14+q*5,5+q*2,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle="#d08c72";ctx.lineWidth=6;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-5,8);ctx.quadraticCurveTo(0,-rise-8,7,-rise);ctx.stroke();ctx.strokeStyle="#f0ad91";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-4,5);ctx.quadraticCurveTo(1,-rise-6,6,-rise+1);ctx.stroke();ctx.fillStyle="#6b4c34";for(let i=0;i<5;i++){const a=i*1.3;ctx.beginPath();ctx.arc(Math.cos(a)*(8+q*12),8+Math.sin(a)*4,2,0,Math.PI*2);ctx.fill();}ctx.restore();\n    }else if(s.type==="wormStampedeBanner"){const q=1-Math.max(0,s.life)/(s.maxLife||.85);ctx.save();ctx.translate(s.x,s.y);ctx.globalAlpha=Math.max(0,1-q);ctx.fillStyle="#f2b28f";ctx.strokeStyle="#4b2e22";ctx.lineWidth=3;ctx.font="bold 14px system-ui";ctx.textAlign="center";ctx.strokeText("WORM STAMPEDE!",0,-30-q*12);ctx.fillText("WORM STAMPEDE!",0,-30-q*12);ctx.restore();\n'''
s=s.replace(draw_anchor,draw+draw_anchor,1)
p.write_text(s,encoding='utf-8');print('Added Worm Stampede')