from pathlib import Path
p=Path('index.html')
s=p.read_text()
old='''function createSlot(slot){\n  const raw=prompt(`Name Save ${slot}:`,`Adventure ${slot}`);if(raw===null)return;const name=(raw.trim()||`Save ${slot}`).slice(0,24);\n  localStorage.setItem(SAVE_SLOT_PREFIX+slot,JSON.stringify({version:2,name,savedAt:new Date().toISOString(),save}));\n  localStorage.setItem(ACTIVE_SLOT_KEY,String(slot));renderSaveSlots();setSaveStatus(`${name} created from your current progress. Autosave is on.`);\n}'''
new='''function createSlot(slot){\n  let modal=document.getElementById("createSaveModal");\n  if(modal)modal.remove();\n  modal=document.createElement("div");\n  modal.id="createSaveModal";\n  modal.className="modal show";\n  modal.innerHTML=`<div class="sheet" style="max-width:430px">\n    <h2 style="margin-bottom:8px">Create Save ${slot}</h2>\n    <div class="small" style="margin-bottom:10px">Give this save a name. Your progress will autosave to this slot while you play.</div>\n    <input id="createSaveName" maxlength="24" value="Adventure ${slot}" autocomplete="off" style="width:100%;padding:13px 12px;border-radius:12px;border:1px solid #46705e;background:#0b1d16;color:#f4fff8;font:inherit;font-size:16px;outline:none" />\n    <div style="display:flex;gap:8px;margin-top:14px">\n      <button class="secondary" id="cancelCreateSave" style="flex:1">Cancel</button>\n      <button class="primary" id="confirmCreateSave" style="flex:1">Create Save</button>\n    </div>\n  </div>`;\n  document.body.appendChild(modal);\n  const input=modal.querySelector("#createSaveName");\n  const close=()=>modal.remove();\n  const confirmCreate=()=>{\n    const name=((input.value||"").trim()||`Save ${slot}`).slice(0,24);\n    localStorage.setItem(SAVE_SLOT_PREFIX+slot,JSON.stringify({version:2,name,savedAt:new Date().toISOString(),save}));\n    localStorage.setItem(ACTIVE_SLOT_KEY,String(slot));\n    close();\n    renderSaveSlots();\n    setSaveStatus(`${name} created from your current progress. Autosave is on.`);\n    showScreen("homeScreen");\n  };\n  modal.querySelector("#cancelCreateSave").addEventListener("click",close);\n  modal.querySelector("#confirmCreateSave").addEventListener("click",confirmCreate);\n  input.addEventListener("keydown",e=>{if(e.key==="Enter")confirmCreate();});\n  setTimeout(()=>{input.focus();input.select();},50);\n}'''
if old not in s:
    raise SystemExit('createSlot anchor not found')
s=s.replace(old,new,1)
p.write_text(s)
print('Updated empty save slots to use an in-game create-save modal.')
