name: Make end base fully visible
on:
  push:
    paths:
      - '.github/workflows/move-base-onscreen-once.yml'
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move base fully onto map
        run: python3 .github/move-base-onscreen.py
      - name: Commit update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm .github/workflows/move-base-onscreen-once.yml .github/move-base-onscreen.py
          git add index.html
          git commit -m "Make road end at a fully visible base"
          git push
